site_name: GoalFinch Documentation

theme:
  name: material
  favicon: favicon.ico
  logo: goldfinch-logo.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: amber
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: amber
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
