sites:
  - name: goalfinch-site
    build:
      base: /
      command: 
      publish: site/
      ignore: git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF site/
    edge_functions: []
    functions: {}
    headers: []
    redirects: []
    environment:
      NODE_VERSION: "18"

  - name: goalfinch-docs
    build:
      base: /
      command: mkdocs build -d build
      publish: build/
      ignore: git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF docs/
    edge_functions: []
    functions: {}
    headers: []
    redirects: []
    environment:
      PYTHON_VERSION: "3.11"

  - name: goalfinch-app
    build:
      base: ui/
      command: npm run build
      publish: ui/build/
      ignore: git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ui/
    edge_functions: []
    functions: {}
    headers: []
    redirects: []
    environment:
      NODE_VERSION: "18"
