site_name: Goal Finch Technical Documentation
site_url: https://docs.goalfinch.com

nav:
  - Home: index.md
  - Tutorials:
    - Connect to data in Google Sheets: tutorials/connect-to-data-in-google-sheets.md
    - Use Goal Finch as your new tab background in Chrome: tutorials/use-goalfinch-as-your-new-tab-background-in-chrome.md
    - Share pictures in a public S3 bucket: tutorials/share_pictures_in_s3.md
    # - Set up a self-hosted backend: tutorials/set-up-a-self-hosted-backend.md
    # - Log events via API: tutorials/log-events-via-api.md
  - Architecture:
    - Deployment patterns: architecture/deployment-patterns.md
    - Frontend: architecture/frontend.md
    # - Backend: architecture/backend.md
  # - API Reference:
  #   - Authentication: api/authentication.md
  #   - Endpoints: api/endpoints.md
  # - Contributing:
  #   - Development Setup: contributing/development-setup.md
  #   - Guidelines: contributing/guidelines.md

theme:
  name: material
  favicon: favicon.ico
  logo: goldfinch-logo.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: amber
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: amber
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css
