[[sites]]
  name = "goalfinch-app"

  [sites.build]
    base = "/"
    command = "pnpm build"
    publish = "dist/"
    edge_functions = []
    functions = {}
    headers = []
    redirects = []

  [sites.environment]
    NODE_VERSION = "20"
