[[sites]]
  name = "goalfinch-app"
  
  [sites.build]
    base = "/"
    command = "npm run build"
    publish = "build/"
    edge_functions = []
    functions = {}
    headers = []
    redirects = []
  
  [sites.environment]
    NODE_VERSION = "20"
